name: Build Plugin

on:
   push:
      branches:
         - main
   pull_request:

jobs:
   gradle:
      strategy:
         matrix:
            os: [ubuntu-latest]
      runs-on: ${{ matrix.os }}
      steps:
         - uses: actions/checkout@v4
         - uses: actions/setup-java@v4
           with:
               distribution: temurin
               java-version: 17

         - name: Setup Gradle
           uses: gradle/actions/setup-gradle@v4

         - name: Execute Gradle build
           run: ./gradlew buildPlugin --no-daemon

         - uses: actions/upload-artifact@v4
           with:
             name: ethersync-plugin.zip
             path: build/distributions/ethersync-*.zip
