name: Build Plugin

on:
   push:
      branches:
         - main

jobs:
   gradle:
      strategy:
         matrix:
            os: [ubuntu-latest]
      runs-on: ${{ matrix.os }}
      steps:
         - uses: actions/checkout@v4
         - uses: actions/setup-java@v4
           with:
               distribution: temurin
               java-version: 21

         - name: Setup Gradle
           uses: gradle/actions/setup-gradle@v4

         - name: Execute Gradle build
           run: ./gradlew buildPlugin

         - name: Create nightly release
           id: create_release
           uses: viperproject/create-nightly-release@v1
           env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           with:
              tag_name: nightly
              release_name: Ethersync Jetbrains Nightly
              body_path: ./build/distributions/ethersync-0.7.0-SNAPSHOT.zip
              keep_num: 0
              keep_tags: false
