name: Build Plugin

on:
   push:
      branches:
         - main
   pull_request:

jobs:
   gradle:
      strategy:
         matrix:
            os: [ubuntu-latest]
      runs-on: ${{ matrix.os }}
      steps:
         - uses: actions/checkout@v4
         - uses: actions/setup-java@v4
           with:
               distribution: temurin
               java-version: 21

         - name: Setup Gradle
           uses: gradle/actions/setup-gradle@v4

         - name: Execute Gradle build
           run: ./gradlew buildPlugin

         - name: Deploy ethersync main
           uses: WebFreak001/deploy-nightly@v3.1.0
           with:
               upload_url: https://uploads.github.com/repos/ethersync/ethersync-jetbrains/releases/1/assets{?name,label}
               release_id: 1
               asset_path: ./build/distributions/ethersync-*.zip
               asset_name: ethersync-jetbrains-nightly-$$.zip
               asset_content_type: application/zip
               ignore_hash: true
